# Default value.
newline_style = "Unix"
fn_return_indent = "WithWhereClause"
fn_args_paren_newline = false
fn_args_layout = "Block"
where_trailing_comma = true
chain_base_indent = "Inherit"
chain_indent = "Tabbed"
# Default value.
# Separate `std`, other crates, and `self` manually.
reorder_imports = false
match_block_trailing_comma = true
