# See <https://github.com/rust-lang-nursery/rustfmt/issues/2227>.
unstable_features = true

blank_lines_upper_bound = 2  # From 0.2.17
error_on_line_overflow = false
match_block_trailing_comma = true
newline_style = "Unix"  # Default.
# Separate `std`, other crates, and `self` manually.
reorder_imports = false  # Default.
trailing_comma = "Vertical"  # Default.

# This file is for =rustfmt-nightly-0.3.4
